@startuml
start
    repeat
        :Scan QR Code with camera
        let image = camera.scan();
        :QRItemLookup.convertQRCodeToItemId(image);
    backward :<color:#red>**Show Invalid QR Code Error Dialog**;

    repeat while (Is valid QR Code?) is (no)
        
    ->yes;
    :let selectedItem = Lookup ItemID (from QR Code)
    in ItemDatabase;
    if (selectItem is null?) then (yes)
        :<color:#red>**Show Item is Not Available Dialog**;
        
    else (no)
        #FFE6CC:Get Item Details of selectedItem 
        from WarehouseInventory
        (price, recommendations,  
        reviews, available quantity);
        :set availableQty = available quantity;

        :Display Item Details for selectedItem;
        :Display Get Quantity for Item Dialog;
        repeat
        :let selectedQty = Get item quantity input from user;
        backward: :<color:#red>**Show Not Enough Available Items Dialog**;
        repeat while (selectedQty > availableQty) is (yes)
        ->no;
        :User taps 'Add Item to Cart Button';
        :Send Add Item to Cart notification in queue;
    endif
    stop
@enduml